apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: ocp4-pb9pp
  name: ocp4-pb9pp-windows-worker-us-east-2b
  namespace: openshift-machine-api
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: ocp4-pb9pp
      machine.openshift.io/cluster-api-machineset: ocp4-pb9pp-windows-worker-us-east-2b
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: ocp4-pb9pp
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: ocp4-pb9pp-windows-worker-us-east-2b
        machine.openshift.io/os-id: Windows 
    spec:
      metadata:
        labels:
          node-role.kubernetes.io/worker: "" 
      providerSpec:
        value:
          ami:
            id: ami-0710f0d84bb7d9df1
          apiVersion: awsproviderconfig.openshift.io/v1beta1
          blockDevices:
            - ebs:
                iops: 0
                volumeSize: 120
                volumeType: gp2
          credentialsSecret:
            name: aws-cloud-credentials
          deviceIndex: 0
          iamInstanceProfile:
            id: ocp4-pb9pp-worker-profile 
          instanceType: m5a.xlarge
          kind: AWSMachineProviderConfig
          placement:
            availabilityZone: us-east-2b
            region: us-east-2
          securityGroups:
            - filters:
                - name: tag:Name
                  values:
                    - ocp4-pb9pp-worker-sg 
          subnet:
            filters:
              - name: tag:Name
                values:
                  - ocp4-pb9pp-private-us-east-2b
          tags:
            - name: kubernetes.io/cluster/ocp4-pb9pp
              value: owned
          userDataSecret:
            name: windows-user-data 
            namespace: openshift-machine-api
